#!/usr/bin/env python3
"""Generate the single-precision Taylor-Green vortex sources from the
double-precision ones, so the two can never drift apart.

    to_single_precision.py <src_dir> <out_dir>

Converted (tokenized, so strings, comments and identifiers are safe):
  * the `double` keyword            -> `float`
  * the "double" type-name strings  -> "float"   (ops_decl_dat, ops_arg_dat,
                                                  ops_decl_const, HDF5 consts)
  * every floating literal          -> `f` suffix (1.0 -> 1.0f, 1e-3 -> 1e-3f)
  * M_PI (a double macro)           -> a float literal
  * <math.h> calls sin, cos, ...    -> sinf, cosf, ... so float arguments do not
                                       bind to the double overloads

A literal that stayed `double` would promote the whole expression to double
(an implicit upcast); a double-only math call would promote its argument. Both
are what KernelIRBuilder's strict mode (OPS_MLIR_STRICT_FP=1) rejects, and
check_single_precision.py verifies the output.

Left as double on purpose: host wall-clock timers (cpu_*, elapsed_*,
partition_*, inner_*) because ops_timers() takes double*. diagnostics.h,
bc_exchanges.h and stencils.h are copied verbatim (diagnostics.h is written
against real_t and reports in double).
"""
import os
import re
import sys

CONVERT = ["constants.h", "opensbliblock00_kernels.h", "defdec_data_set.h",
           "io.h", "opensbli.cpp"]
COPY = ["bc_exchanges.h", "stencils.h", "diagnostics.h"]

KEEP_DOUBLE = re.compile(r"^(cpu_|elapsed_|partition_|inner_)")
MATH = {"sin", "cos", "tan", "asin", "acos", "atan", "atan2", "sinh", "cosh",
        "tanh", "exp", "exp2", "log", "log2", "log10", "sqrt", "pow", "fabs",
        "floor", "ceil"}
PI_F = "3.14159265358979323846f"

TOKEN = re.compile(r"""
    (?P<ws>\s+)
  | (?P<lc>//[^\n]*)
  | (?P<bc>/\*.*?\*/)
  | (?P<str>"(?:\\.|[^"\\])*")
  | (?P<chr>'(?:\\.|[^'\\])*')
  | (?P<num>\.?\d(?:[eE][+-]|[\w.'])*)
  | (?P<id>[A-Za-z_]\w*)
  | (?P<other>.)
""", re.X | re.S)


def tokenize(text):
    return [(m.lastgroup, m.group()) for m in TOKEN.finditer(text)]


def is_float_literal(t):
    if t[:2] in ("0x", "0X"):
        return False
    return "." in t or re.search(r"\d[eE][+-]?\d", t) is not None


def convert(text):
    toks = tokenize(text)
    out = []
    for i, (kind, t) in enumerate(toks):
        if kind == "num" and is_float_literal(t) and t[-1] not in "fFlL":
            t += "f"
        elif kind == "str" and t == '"double"':
            t = '"float"'
        elif kind == "id":
            nxt = next((x for x in toks[i + 1:] if x[0] != "ws"), ("", ""))
            if t == "M_PI":
                t = PI_F
            elif t == "double":
                # Keep host timer declarations: `double cpu_start0, ...;`
                j = i + 1
                while j < len(toks) and (toks[j][0] == "ws" or toks[j][1] in ("*", "&", "const")):
                    j += 1
                name = toks[j][1] if j < len(toks) else ""
                if not KEEP_DOUBLE.match(name):
                    t = "float"
            elif t in MATH and nxt[1] == "(":
                t += "f"
        out.append(t)
    return "".join(out)


def main():
    src, dst = sys.argv[1:3]
    os.makedirs(dst, exist_ok=True)
    banner = ("// GENERATED by to_single_precision.py from {} -- do not edit.\n")
    for name in CONVERT:
        with open(os.path.join(src, name)) as f:
            text = f.read()
        with open(os.path.join(dst, name), "w") as f:
            f.write(banner.format(name) + convert(text))
    for name in COPY:
        with open(os.path.join(src, name)) as f:
            text = f.read()
        with open(os.path.join(dst, name), "w") as f:
            f.write(text)


if __name__ == "__main__":
    main()
